# Generated by Django 5.0.6 on 2024-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_employeerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserTypeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DimEmployeeRole',
            },
        ),
    ]
