# Generated by Django 5.0.6 on 2024-06-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team_teamdescription_alter_team_departmentid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriorityName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'DimPriority',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'DimStatus',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Description', models.TextField()),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('TaskStartDate', models.DateField(blank=True, null=True)),
                ('TaskDueDate', models.DateField(blank=True, null=True)),
                ('AssignedUserId', models.ManyToManyField(related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('CreatorUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PriorityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priority')),
                ('StatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('TeamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
