# Generated by Django 5.0.6 on 2024-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_priority_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='StatusName',
            field=models.CharField(max_length=50),
        ),
    ]
